### ISSUE TITLE
unable to draw on canvas

### ISSUE THREAD

**Issue by Fasih1994** [vutsalsinghal/Django_MNIST_wrapper#2]
may be function need some code thanks for help

{% block load_js %}
(function()
{ 
	var canvas = document.querySelector( "#canvas" );
	var context = canvas.getContext( "2d" );
	canvas.width = 280;
	canvas.height = 280;

	var Mouse = { x: 0, y: 0 };
	var lastMouse = { x: 0, y: 0 };

**Comment by vutsalsinghal** [comment]
The **drawing** part seems to be working just fine. Check the deployed site here https://pyofeyblog.pythonanywhere.com/mnist

Maybe I'm missing something. Could you kindly send a PR please.
